### ISSUE TITLE
The schema editor web UI loses the types of schema field values

### ISSUE THREAD

**Issue by seanh** [ckan/ckanext-datapackager#10]
When a schema for a CSV file is first generated it can have field values of different types (string, integer, etc.):

    name: "yearID",
    count: 169,
    ...

But if you edit this schema using the schema editor web interface, even if you don't edit the value of the `count` field it'll get turned into a string:

    name: "yearID",
    count: "169",
    ...

This isn't apparent when looking at the schema in the web interface, but you can see it if you view the schema in the API or in the data package download.

The problem is that when you submit the form, all the fields come into the Python code as strings, there's nothing in the form to tell the Python code that one field value is an integer or something else.

One solution might be to add a dropdown list of types next to each field value in the schema so the user can tell the server what type they intend each value to be. This might even improve the UI - if they set the type to Integer we can replace the text field for the value with a number picker, if they set the type to Date we can use a calendar widget, etc.

**Comment by vitorbaptista** [comment]
Closed as not relevant anymore after https://github.com/ckan/ckanext-datapackager/issues/25
