### ISSUE TITLE
Broken breadcrumbs on package pages

### ISSUE THREAD

**Issue by seanh** [ckan/ckanext-datapackager#12]
The breadcrumbs on pages like this one <http://datapackager.okfn.org/package/my-first-tabular-data-package/> are broken when no one's logged in, I see:

    Home / / My first Tabular Data Package

Should be:

    Home / Sean Hammond / My first Tabular Data Package

(Where Sean Hammond links to Sean Hammond's user profile page.)

If you are logged-in as a different user, I think you'll see:

    Home / Joe Smith / My first Tabular Data Package

Which is also wrong.

**Comment by vitorbaptista** [comment]
Closed as not relevant anymore after https://github.com/ckan/ckanext-datapackager/issues/25
