### ISSUE TITLE
Get rid of scrollbar in metadata viewer and editor

### ISSUE THREAD

**Issue by seanh** [ckan/ckanext-datapackager#13]
When viewing or editing a CSV file, the metadata area to the left of the CSV preview will have a scrollbar if the metadata is too long:

![screenshot from 2014-06-14 16 11 13](https://cloud.githubusercontent.com/assets/22498/3278696/de3543f2-f3cd-11e3-9a6c-870386f62b90.png)

This is particularly awkward when editing the metadata.

It would be nice if the whole metadata / CSV preview box would be as tall as either the metadata part or the CSV preview part, whichever is taller, so that there's never a scrollbar.

**Comment by vitorbaptista** [comment]
Closed as not relevant anymore after https://github.com/ckan/ckanext-datapackager/issues/25
