### ISSUE TITLE
"Add New Resource" and "New resource" show when adding a new file to a package

### ISSUE THREAD

**Issue by seanh** [ckan/ckanext-datapackager#15]
Go to a data package's page, click Edit, click Data files, click Add new file -> the add new file page contains the texts "Add New Resource" and "New resource". We don't use the word "resource" in Data Packager (we just call them files), so these should be "Add new file" and "New file".

**Comment by vitorbaptista** [comment]
Closed as not relevant anymore after https://github.com/ckan/ckanext-datapackager/issues/25
