### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckanext-datapackager#36]
This would require moving the dependencies into `setup.py`. I wasn't able to setup `datapackage` into `setup.py` with github inside the `dependency_requires`. We might need to wait until `datapackage` is published to PyPI.

**Comment by vitorbaptista** [comment]
The `datapackage` version on PyPI is different than the one we use here, so this depends on #45. After that is done, this issue should be simply pushing to PyPI and testing that everything went OK.

**Comment by vitorbaptista** [comment]
I imagine the only thing missing here is actually pushing to PyPI, right @k-nut ?

**Comment by k-nut** [comment]
@vitorbaptista and there it is: https://pypi.python.org/pypi/ckanext-datapackager/0.2.0

I just installed it locally with `pip install ckanext-datapackager` (so from PyPi live) and it seems to work just like it is supposed to.

Should we mark this as closed?

**Comment by pwalsh** [comment]
nice work

**Comment by vitorbaptista** [comment]
@k-nut Brilliant! Please add myself (vitorbaptista), pwalsh and okfn as owners of it on PyPI :+1:

**Comment by k-nut** [comment]
@vitorbaptista done! `Package Index Owner: okfn, pwalsh, vitorbaptista, k-nut`
