### ISSUE TITLE
Should we partially import datapackages?

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckanext-datapackager#41]
Consider the following datapackage:

```json
{
    "name": "foo",
    "resources": [
        {"path": "inexistent-file.csv"},
        {"path": "valid-file.csv"}
    ]
}
```

The current process of importing a datapackage works as:
1. Create the CKAN Dataset;
2. Create each resource.

If an exception is thrown while creating a new resource, the dataset is still created. The root issue is that we can't upload resources using CKAN's `package_create` (even though the docs say we are), so we have to call `package_create` once for creating the dataset, then `resource_create` for each resource, then finally `package_show` to get the dataset with all its resources and return to the user.

If we don't want to partially import datapackages, we would have to do something like:

1. Create CKAN Dataset;
2. Create each resource inside a transaction;
3. Were there any errors?
  1. If yes, delete the created dataset;
  2. If not, move on.

The step `3.i` is tricky, because there might be an error when deleting the dataset. Ideally, everything would be inside a single transaction and this all-or-nothing would be taken care for us. Unfortunately, that wouldn't work because we need the dataset's ID to create the resources, and we only have its ID when it's commited to the database. It might be easier to simply fix CKAN's `package_create`, allowing us to create the dataset and its resources in one go.

If we do want to partially import datapackages, we should simply catch any exceptions thrown while creating the resources and show them to the user afterwards, but redirect her to the newly created dataset anyway.

/cc @amercader @pwalsh

**Comment by pwalsh** [comment]
partial import: I'd say no in this case.

About ID - is it not a UUID in CKAN, so we can create it in python and pass it in on create (and therefore also have it available for the resources)?

**Comment by pwalsh** [comment]
also we especially can't have partial import if we don't have a robust way to update an existing DP.

**Comment by amercader** [comment]
I'd also prefer to delete the whole datasets if a resource fails. Would it help to create the dataset as `state=draft` and only make it active if everything went well?

@pwalsh Vitor means the internal CKAN id, not the DP one. We need that one to link resources to the dataset

**Comment by pwalsh** [comment]
@amercader i get it. I was (wrongly) assuming that CKAN might use UUIDs as primary keys.

**Comment by amercader** [comment]
Probably irrelevant to Vitor's issue but CKAN does use UUIDs as PK

**Comment by pwalsh** [comment]
@amercader ok, maybe irrelevant, but he said he needs the PK of the dataset before it is committed to the DB, so that is why I thought he can do so by generating in Python. But yeah. I'm not sure on this particular case.

**Comment by vitorbaptista** [comment]
Talking with @amercader, we agreed that the best approach is:

1. Create dataset as draft;
2. Create the resources;
3. Were there any errors?
    1. If yes, delete the dataset (`package_delete`);
    2. If not, move on.

We won't handle the case where an exception happens when deleting the dataset. It should be extremely rare, so it's a risk worth taking in our opinion.

@pwalsh's workaround of generating an UUID ourselves works, but requires changing CKAN's schema, as by default it ignores an "id" field.

The only safe way of doing it would be to wrap everything inside a transaction, but that would require changing CKAN core's `package_create`. That's worthwhile in my opinion, as it's one of the most important API calls. This isn't blocked by it, though.

**Comment by wardi** [comment]
setting package ids has been allowed for sysadmins since ckan 2.3. https://github.com/ckan/ckan/blob/release-v2.3/ckan/logic/schema.py#L140

**Comment by vitorbaptista** [comment]
Oh, didn't know that. Thanks for the pointer, @wardi.

I don't think we can use it in this case, as we're creating a new API endpoint that can be used by regular users. We could hack our way around checking the permissions ourselves and using a sysadmin user, but I don't think that's a good idea.

I've wrote some code to solve this issue in https://github.com/ckan/ckanext-datapackager/commit/3dad1076b51b6d3baa339e160fa5f6f807c7555d, but I'm still hunting down the source of an error (`SearchIndexError: I/O operation on closed file`, https://travis-ci.org/ckan/ckanext-datapackager/builds/102438215). Hopefully, it won't take long.

**Comment by wardi** [comment]
I agree. Letting normal users set package ids on a ckan site is probably a bad idea.

**Comment by vitorbaptista** [comment]
After loosing a few hours debugging the `SearchIndexError` exception, I found out that it was being caused by HTTPretty. I changed the test not to use it, and everything is green again.

This is done now.
